newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.newyear, name="newyear"),
    path('<str:name>', views.greet, name="greet"),
]

project1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls")),
   
]

tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path('', views.index, name="index"),
    path('add/', views.add, name="add"),
]

newyear/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models

# Create your models here.

newyear/views.py
from django.shortcuts import render

# Create your views here.
def newyear(request):
    return render(request, "newyear/index.html")

def greet(request, name):
    return render(request, "newyear/greet.html", {
        "name": name.upper(),
    })

tasks/views.py
from django.shortcuts import render

tasks=["foo","bar", "baz"]
# Create your views here.
def index(request):
    return render(request, "tasks/index.html",{
        "tasks":tasks
    })

def add(request):
    return render(request,"tasks/add.html")

newyear/templates/newyear/greet.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="{% static 'newyear/styles.css'%}" rel="stylesheet">
</head>
<body>
    <h1> hello {{ name}}</h1>
</body>
</html>

newyear/templates/newyear/index.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Is it new year</title>
    <link href="{%static 'newyear/styles.css'%}" rel="stylesheet">
    
</head>
<body>
    <h1>YES</h1>
</body>
</html>

tasks/templates/tasks/add.html
{% extends "tasks/layout.html"%}

{% block body%}
    <h1>Add task</h1>
    <form action="{% url 'tasks:add'%}" method="POST">
        {% csrf_token %}
        <input type="text" name="task">
        <input type="submit" value="Submit">
    </form>
    <a href="{% url 'tasks:index' %}">View task</a>
{%endblock%}

tasks/templates/tasks/index.html
{%extends "tasks/layout.html"%}
{% block body %}
<h1> Tasks</h1>
    <ul>
        {% for task in tasks %}
            <li>{{task}}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}">Add a new task</a>

{% endblock %}

tasks/templates/tasks/layout.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
    <link href="{% static 'tasks/styles.css'%}" rel="stylesheet">
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>